# ============================================================
#  AquaControl - Configuración de la aplicación
#  Proyecto III - Universidad Mariano Gálvez de Guatemala
# ============================================================

# --- Base de Datos MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/aquacontrol_db?useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=adminGT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Servidor ---
server.port=8080

# --- JWT ---
aquacontrol.jwt.secret=AquaControlSecretKey2026UMGProyectoIIISecureTokenKey256Bits
aquacontrol.jwt.expiration=28800000

# --- Nombre de la aplicación ---
spring.application.name=AquaControl
